wandb_version: 1

npk:
  desc: null
  value:
    seed: 0
    path: /Users/wsolow/Projects/agaid_crop_simulator/
    output_vars:
    - DVS
    - LAI
    - RD
    - WSO
    - NuptakeTotal
    - PuptakeTotal
    - KuptakeTotal
    - NAVAIL
    - PAVAIL
    - KAVAIL
    - WC
    weather_vars:
    - IRRAD
    - TMIN
    - TMAX
    - TEMP
    - VAP
    - RAIN
    - WIND
    intvn_interval: 1
    num_fert: 2
    num_irrig: 2
    n_recovery: 0.7
    p_recovery: 0.7
    k_recovery: 0.7
    fert_amount: 2
    irrig_amount: 0.5
    beta: 10.0
    agro_fpath: env_config/agro_config/test_agro_npk.yaml
    crop_fpath: env_config/crop_config/
    site_fpath: env_config/site_config/
    random_reset: false
exp_name:
  desc: null
  value: ppo
seed:
  desc: null
  value: 1
torch_deterministic:
  desc: null
  value: true
cuda:
  desc: null
  value: true
track:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: ppo_npk
wandb_entity:
  desc: null
  value: null
capture_video:
  desc: null
  value: false
env_id:
  desc: null
  value: npk-v0
total_timesteps:
  desc: null
  value: 500000
learning_rate:
  desc: null
  value: 0.00025
num_envs:
  desc: null
  value: 4
num_steps:
  desc: null
  value: 128
anneal_lr:
  desc: null
  value: true
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
num_minibatches:
  desc: null
  value: 4
update_epochs:
  desc: null
  value: 4
norm_adv:
  desc: null
  value: true
clip_coef:
  desc: null
  value: 0.2
clip_vloss:
  desc: null
  value: true
ent_coef:
  desc: null
  value: 0.01
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
target_kl:
  desc: null
  value: null
batch_size:
  desc: null
  value: 512
minibatch_size:
  desc: null
  value: 128
num_iterations:
  desc: null
  value: 976
_wandb:
  desc: null
  value:
    code_path: code/train_agent.py
    python_version: 3.10.9
    cli_version: 0.17.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724879771
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.10.9
      5: 0.17.7
      8:
      - 5
      13: darwin-arm64
